alias msa="zypper"
alias gtlex="cd /run/media/abrarshakhi/Lexur"
alias gtcp="cd /run/media/abrarshakhi/Lexur/codebox/cp"
alias cls="clear"
alias del="rm -rf"
alias qa="exit"
alias osup="sudo zypper ref && sudo zypper dup"
